#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countingValleys' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER steps
#  2. STRING path
#

def countingValleys(steps, path):
    # Write your code here
    count=0
    traverse=0
    x=list()
    for i in path:
        if i=="D":
            traverse-=1
        else:
            traverse+=1
        x.append(traverse)
    for i in range(len(x)):
        if x[i]<0 and x[i+1]>=0:
            count+=1
    return count    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    steps = int(input().strip())

    path = input()

    result = countingValleys(steps, path)

    fptr.write(str(result) + '\n')

    fptr.close()
