#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort1' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort1(n, arr):
    # Write your code here
    x=arr[-1]
    f=False
    for i in range(-2,-n-1,-1):
        if x<arr[i]: 
            arr[i+1]=arr[i]
            s=""
            for a in arr: s+=str(a)+" "
            print(s)
        elif x> arr[i]:
            arr[i+1]=x
            s=""
            for a in arr: s+=str(a)+" "
            print(s)
            break
        if i==-n:
            arr.pop(0)
            arr.insert(0,x)
            s=""
            for a in arr: s+=str(a)+" "
            print(s)
            break
if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort1(n, arr)
